
development:
  cloud_name: <%= Rails.application.credentials.fetch(:cloud_name)%>
  api_key: <%= Rails.application.credentials.fetch(:api_key)%>
  api_secret: <%= Rails.application.credentials.fetch(:api_secret)%>
  secure: <%= Rails.application.credentials.fetch(:secure)%>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= Rails.application.credentials.fetch(:cloud_name)%>
  api_key: <%= Rails.application.credentials.fetch(:api_key)%>
  api_secret: <%= Rails.application.credentials.fetch(:api_secret)%>
  secure: <%= Rails.application.credentials.fetch(:secure)%>
  enhance_image_tag: true
  static_file_support: false
test:
  cloud_name: <%= Rails.application.credentials.fetch(:cloud_name)%>
  api_key: <%= Rails.application.credentials.fetch(:api_key)%>
  api_secret: <%= Rails.application.credentials.fetch(:api_secret)%>
  secure: <%= Rails.application.credentials.fetch(:secure)%>
  enhance_image_tag: true
  static_file_support: false



